language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.5-dev" # 3.5 development branch
    - "3.6-dev" # 3.6 development branch
    - "nightly" # currently points to 3.7-dev
before_install:
    - pip install -r requirements.txt
install:
    - pip install coveralls codeclimate-test-reporter
    - python setup.py install
script:
    - nosetests -v
    - coverage run --source=prayertimes setup.py test
    - coverage run --source=prayertimes prayertimes/prayertimes.py
after_success:
    - bash <(curl -s https://codecov.io/bash)
    - coveralls
    - CODECLIMATE_REPO_TOKEN=de640a18b9ebdfba184c7260e57f8ba5d6f3aec16d1882fd4770aca5e2a2b45b codeclimate-test-reporter